id = "aquaflow-theme"
name = "Aquaflow Theme"
description = "A calm, ocean-inspired greenish theme for Zed. Soft gradients and highly readable colors."
version = "1.0.1"
schema_version = 1
repository = "https://github.com/Whitfrost21/zed-Aquaflow"
authors = ["Prajwal Zore"]
themes = ["themes/aquaflow.json"]
